Develop
7Jenko/java-filmorate pull request #32
Opened 2024-12-18 19:26 UTC by 7Jenko

2024-12-18 22:41 UTC, 7Jenko commented
@slavrikk , у нас вышла проблемная ситуация, в которой из-за закрытого ранее пул реквеста https://github.com/7Jenko/java-filmorate/pull/16 , не получается нормально сделать этот.
То есть для решения конфликтов нужно подмерджить main, что убираете все остальные новые классы
![image](https://github.com/user-attachments/assets/02efda08-59f2-45f1-8940-d72480011d44)
Ты сможешь посмотреть, загрузив себе ветку develop локально, пожалуйста? Или если знаешь, как решить эту проблему, будем благодарны за помощь.

2024-12-19 01:01 UTC, slavrikk commented
только делать ребейз ветки main на develop и вручную править конфликты, больше к сожалению не смогу посмотреть так как нахожусь в отпуске

2024-12-20 14:05 UTC, EugeneLenkevich requested changes
Привет, Денис! Спасибо за PR.
Что то в ПР-е мало изменений, судя по комментариям что то там лишнего смержили

![image](https://github.com/user-attachments/assets/d2636a19-a420-490e-b1e5-82289be6983a)

Давай попробуем разобраться что тут делать, это же групповой проект, верно?
Через force push можно делов наворотить, предложу оставить пока develop как есть, но создадим новую ветку от main, смержим в нее другие фича-ветки(как до этого делали, ветки наверно еще остались, если нет, то можно сделать cherry pick нужных комитов) и уже ее отправим на ревью. Иначе очень трудно будет проверять решение. Если что пиши, попробуем разобраться

2024-12-23 15:12 UTC, 7Jenko commented
@EugeneLenkevich Привет. Мало изменений из-за того, что я случайно сделал мердж новой фичи в main вместо develop, а потом сделал revert. У нас Максим нашел такую информацию: "При попытке создать новый пулл-реквест из второстепенной ветки в основную, Git видит, что изменения, которые ты пытаешься внести, уже были в основной ветке и были отменены. Поэтому в интерфейсе GitHub показывается, что нет изменений"
Исходя из этого, созданные новые ветки от main тоже видят эти изменения и новые фичи прикручиваются ровно таким же количеством изменений. Если знаешь еще какой-то способ, поделись, пожалуйста. Будем пробовать
Так же пробовал сделать hard reset main, но в итоге он и при merge и при rebase все равно подтягивает историю коммитов с этими отмененными изменениями.

2024-12-23 17:05 UTC, EugeneLenkevich requested changes
Привет, Денис! Спасибо за PR.

В целом все гут. 
Что хочется поправить в первую очередь
- разобраться с логами
- одинаковые вещи хочется делать единым образом

в общем, отметил комментариями, посмотри, пожалуйста :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam String sortBy) {
String sortBy

А что если мы для сортировок сделаем enum, так будет надежней :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.searchFilms(query, by);
А что это за массив строк такой by, не совсем очевидно, хотя можно предположить что сортировка, но тут мы гадаем. Так же, уж не вытаскиваем ли мы детали реализации наружу. Представим себя другим разработчиком, который не видел на код, но ему надо вызывать наш сервис, поймет ли он что надо передать как параметр, скорее всего нет, но если мы ему дадим внятный API, хотя бы ограничим строковые варианты конкретными значениями enum :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        log.debug("Checking existence of director with ID {} for deleting", directorId);
Мы проверяем запись на существование, в принцип это бизнес логика, тут можно и уровень логирования выбрать повыше - info
 log.info(...)

Давай посмотрим на наш код с точки зрения того, кто потом по логам будет разбираться в его работе. У логгера есть несколько уровней - error, info и пр. В принципе какие то тут правил нет, однако, давай приведем все к единому виду и посмотрим что получится, например вот так

- error - нештатные ситуации
- warn - штатные ошибки, та же валидация
- info - бизнес операции, плюс сюда в лог стоит включать какие то базовые идентификаторы, по которым можно будет сопоставлять строки лога с конкретными сущностями
- debug - дополнительная техническая информация, можно содержимое dto распечатывать, например (в реальном приложении только с этим аккуратно, не стоит так раскрывать какую то конфиденциальную информацию)
- trace это совсем какие то мелочи логируются, может даже строчки кода, но нам не надо это особо 

посмотри, пожалуйста, на логи с этой точки зрения, что получится :)

Можно от такое за пример взять(но не обязательно)

log.info Обновление сущности, id=
log.debug dto= {}
log.info Сущность успешно создана

log.warn Ошибка валидации, значение {} недопустимо
log.error Нет соединения с БД

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Long currentId = directorStorage.getAll().stream()
Не уверен что это оптимально сначала доставать, а потом перебирать все записи, на крайний случай лучше делегировать это хранилищу, пусть эта логика будет инкапсулирована внутри хранилища. А еще можно последнее значение в переменной хранить чтобы не перебирать все записи каждый раз :)

Допустим у нас поменяется тип хранилища, стали мы хранить данные в файлах или вовсе СУБД. Высок шанс что у нас с таким подходом будет кончаться память :)
То есть мы отдаем эту обязанность хранилищу, пусть оно решает как оптимальней, и, если что, надо будет переписать один метод хранилища, а не все сервисы которые в себе таскают все данные

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userStorage.getUserById(userId) == null) {
Более наглядней будет если сделаем вот такой метод, посмотри

userStorage.existsById(userId)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if ("year".equalsIgnoreCase(sortBy)) {
"year"

enum так и просится :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            List<Genre> genres = filmGenres.getOrDefault(film.getId(), new ArrayList<>());
А если сделать метод в хранилище, который принимает массив идентификаторов, то мы избавимся тут от цикла и переложим на хранилище обязанность по выборке записей. А выборка данных как раз обязанность хранилища :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                film.setDirectors(null);
filmsDirectors.get(film.getId());

У мапы есть метод getOrDefault, если записей нет то передавать не null а пустой список, тогда можно убрать условие ниже и наш код станет чутка безопасней так как мы используем пустой список, а не null

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.contains("title") && by.contains("director")) {
И вот такую сложную и неочевидную логику мы тащим в контроллер :)
У нас всего три варианта, вот и пусть будет соответствующий enum о трех элементах. Строки - это сложно и легко ошибиться. Плюс мы показываем детали внутренней реализации, это лишняя информация

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        User user = userStorage.getUserById(Math.toIntExact(review.getUserId()));
Тут лучше тоже orElseThrow использовать, вообще всегда лучше одинаковые вещи делать одинаково в рамках проекта, это уменьшает сложность кода :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Film film = filmStorage.getFilmById(Math.toIntExact(review.getFilmId()));
Math.toIntExact

Думается что лучше ли сразу нужные типы использовать чтобы потом их так хитро не приводить :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        }
Опять таки, рамках аж одного метода два разных подхода для одинаковых вещей :)

![image](https://github.com/user-attachments/assets/4981b0a6-0835-430f-abb6-017b9a4a53a8)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewStorage.findById(reviewId).isEmpty()) {
Давай тут лучше сделаем метод, который проверяем запись на существование и возвращает boolean, читаться такой код будет проще так как мы будем пользоваться семантикой предметной области

reviewStorage.existsById(reviewId)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          log.info("Друг успешно добавлен");
log.info("Друг успешно добавлен");

Тут все верно, только лучше в логи добавить идентификаторы чтобы потом по логам можно было определить к какому именно запросу относятся строки лога. Потом же по логам будут разбираться в случае ошибок, а запросов может быть очень много

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.deleteUserById(id)) {
Может стоит явно сделать проверку чтобы не гадать, в одной строчке слишком много логики. К тому же выше мы уже удалили друзей и, если тут мы кинем ошибку, то не получится ли что у нас что данные окажутся в половинчатом виде (если deleteByUserId сам упадет с какой то ошибкой логики) 
Лучше сначала проверить все ли ок, а потом делать, но не одновременно, так сложнее будет данные согласовать в случае нештатных ситуаций :)

2024-12-23 17:05 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public static void validationUserName(User user) {
1. static тут вроде не нужен
2. метод называется validationUserName, а по факту метод обновляет поле, кажется что имя не соответствует тому что метод делает, его бы переименовать или логику организовать по другому :)

2024-12-23 23:34 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        User user = userStorage.getUserById(Math.toIntExact(review.getUserId()));
Исправил.

2024-12-23 23:34 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Film film = filmStorage.getFilmById(Math.toIntExact(review.getFilmId()));
Исправил.

2024-12-23 23:34 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        }
Исправил.

2024-12-23 23:34 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewStorage.findById(reviewId).isEmpty()) {
Исправил.

2024-12-23 23:34 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>          log.info("Друг успешно добавлен");
Исправил.

2024-12-24 04:51 UTC, EugeneLenkevich commented
>пробовал сделать hard reset main, но в итоге он и при merge и при rebase все равно подтягивает историю коммитов с этими отмененными изменениями.

Предположу что hard reset ты сделал на локальной ветке, но когда заливаешь, то есть делаешь push. Git в этот момент мержит локальную ветку с удаленной и потому "возвращает" удаленные комиты, в удаленной то они есть. Тут должен помочь  force push, то есть полное перетирание ветки в репозитории. Главное делов не наворотить в этот момент, очень аккуратно

2024-12-24 18:22 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam String sortBy) {
Денис

2024-12-24 18:22 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.searchFilms(query, by);
Борис

2024-12-24 18:22 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        log.debug("Checking existence of director with ID {} for deleting", directorId);
Борис

2024-12-24 18:24 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Long currentId = directorStorage.getAll().stream()
Максим

2024-12-24 18:24 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if ("year".equalsIgnoreCase(sortBy)) {
Денис

2024-12-24 18:24 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            List<Genre> genres = filmGenres.getOrDefault(film.getId(), new ArrayList<>());
Максим

2024-12-24 18:24 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                film.setDirectors(null);
Денис

2024-12-24 18:25 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.contains("title") && by.contains("director")) {
Борис

2024-12-24 18:25 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.deleteUserById(id)) {
Максим

2024-12-24 18:25 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public static void validationUserName(User user) {
Максим

2024-12-24 18:38 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userStorage.getUserById(userId) == null) {
Исправлено через isEmpty.

2024-12-24 19:28 UTC, EastOf12 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.searchFilms(query, by);
Заменил строки на enum

2024-12-24 19:29 UTC, EastOf12 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        log.debug("Checking existence of director with ID {} for deleting", directorId);
Заменил на log.info

2024-12-24 19:29 UTC, EastOf12 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.contains("title") && by.contains("director")) {
Заменил строки на enum

2024-12-24 22:01 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam String sortBy) {
Исправил

2024-12-24 22:01 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if ("year".equalsIgnoreCase(sortBy)) {
Исправил

2024-12-24 22:02 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                film.setDirectors(null);
Исправил.

2024-12-24 23:46 UTC, kol0sMaksim commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Long currentId = directorStorage.getAll().stream()
Исправлено

2024-12-24 23:47 UTC, kol0sMaksim commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.deleteUserById(id)) {
Исправлено

2024-12-24 23:47 UTC, kol0sMaksim commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public static void validationUserName(User user) {
Исправлено

2024-12-24 23:47 UTC, kol0sMaksim commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            List<Genre> genres = filmGenres.getOrDefault(film.getId(), new ArrayList<>());
Исправлено

2024-12-25 07:11 UTC, EugeneLenkevich requested changes
Моментик с обработкой исключений в контроллере

2024-12-25 07:11 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
Вручную не надо разруливать коды, это лишний код, который только все усложняет. Лучше сделать соответствие кодов и исключений через ControllerAdvice и/или аннотации. Ну и от ResponseEntity лучше избавиться :)

https://struchkov.dev/blog/ru/exception-handling-controlleradvice/

2024-12-25 08:06 UTC, 7Jenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
Исправил.

2024-12-25 08:17 UTC, EugeneLenkevich approved these changes
Во, супер, спасибо

2024-12-25 09:03 UTC, merged